'use strict'

module.exports = {
  NODE_ENV: '"production"'
  FB_DATABASE_URL: '"YOURURL"'
  FB_PROJECT_ID: '"PROJECT_ID"'
  FB_API_KEY: '"FB_API_KEY"'
  FB_AUTH_DOMAIN: '"FB_AUTH_DOMAIN"'
  FB_STORAGE_BUCKET: '"FB_STORAGE_BUCKET"'
  FB_MESSAGE_SENDER_ID: '"FB_MESSAGE_SENDER_ID"'
}
